#pragma once

#include "Event.h"
#include "EventState.h"
#include "EventType.h"
#include "GamepadAxisEvent.h"
#include "GamepadButtonEvent.h"
#include "GamepadConnectEvent.h"
#include "GamepadDisconnectEvent.h"
#include "KeyEvent.h"
#include "MouseButtonEvent.h"
#include "MouseMoveEvent.h"
#include "MouseScrollEvent.h"
#include "WindowCloseEvent.h"
#include "WindowResizeEvent.h"