var annotated_dup =
[
    [ "Minty", "namespace_minty.html", [
      [ "Application", "class_minty_1_1_application.html", "class_minty_1_1_application" ],
      [ "ApplicationBuilder", "struct_minty_1_1_application_builder.html", "struct_minty_1_1_application_builder" ],
      [ "Array", "class_minty_1_1_array.html", "class_minty_1_1_array" ],
      [ "Asset", "class_minty_1_1_asset.html", "class_minty_1_1_asset" ],
      [ "AssetManager", "class_minty_1_1_asset_manager.html", "class_minty_1_1_asset_manager" ],
      [ "AssetManagerBuilder", "struct_minty_1_1_asset_manager_builder.html", "struct_minty_1_1_asset_manager_builder" ],
      [ "Color", "struct_minty_1_1_color.html", "struct_minty_1_1_color" ],
      [ "ConstantContainer", "class_minty_1_1_constant_container.html", "class_minty_1_1_constant_container" ],
      [ "Container", "class_minty_1_1_container.html", "class_minty_1_1_container" ],
      [ "Context", "class_minty_1_1_context.html", "class_minty_1_1_context" ],
      [ "ContextBuilder", "struct_minty_1_1_context_builder.html", "struct_minty_1_1_context_builder" ],
      [ "Counter", "class_minty_1_1_counter.html", "class_minty_1_1_counter" ],
      [ "Debug", "class_minty_1_1_debug.html", "class_minty_1_1_debug" ],
      [ "DualBuffer", "class_minty_1_1_dual_buffer.html", "class_minty_1_1_dual_buffer" ],
      [ "DynamicContainer", "class_minty_1_1_dynamic_container.html", "class_minty_1_1_dynamic_container" ],
      [ "File", "class_minty_1_1_file.html", "class_minty_1_1_file" ],
      [ "FileReaderBehavior", "class_minty_1_1_file_reader_behavior.html", "class_minty_1_1_file_reader_behavior" ],
      [ "FileWriterBehavior", "class_minty_1_1_file_writer_behavior.html", "class_minty_1_1_file_writer_behavior" ],
      [ "is_parseable", "struct_minty_1_1is__parseable.html", null ],
      [ "is_parseable< T, std::enable_if_t< std::is_base_of_v< Parseable, T > > >", "struct_minty_1_1is__parseable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01_parseable_00_01_t_01_4_01_4_01_4.html", null ],
      [ "is_serializable", "struct_minty_1_1is__serializable.html", null ],
      [ "is_serializable< T, std::enable_if_t< std::is_base_of_v< Serializable, T > > >", "struct_minty_1_1is__serializable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_0e61b24cf8de0099628fc4627104c54f1.html", null ],
      [ "is_serializable_object", "struct_minty_1_1is__serializable__object.html", null ],
      [ "is_serializable_object< T, std::enable_if_t< std::is_base_of_v< SerializableObject, T > > >", "struct_minty_1_1is__serializable__object_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__o8b98ea3f58746b2d0c5b18654dddd28a.html", null ],
      [ "JobManager", "class_minty_1_1_job_manager.html", "class_minty_1_1_job_manager" ],
      [ "JobManagerBuilder", "struct_minty_1_1_job_manager_builder.html", "struct_minty_1_1_job_manager_builder" ],
      [ "List", "class_minty_1_1_list.html", "class_minty_1_1_list" ],
      [ "Map", "class_minty_1_1_map.html", "class_minty_1_1_map" ],
      [ "MemoryContainer", "class_minty_1_1_memory_container.html", "class_minty_1_1_memory_container" ],
      [ "MemoryManager", "class_minty_1_1_memory_manager.html", "class_minty_1_1_memory_manager" ],
      [ "MemoryManagerBuilder", "struct_minty_1_1_memory_manager_builder.html", "struct_minty_1_1_memory_manager_builder" ],
      [ "MemoryPool", "class_minty_1_1_memory_pool.html", "class_minty_1_1_memory_pool" ],
      [ "MemoryPoolBuilder", "struct_minty_1_1_memory_pool_builder.html", "struct_minty_1_1_memory_pool_builder" ],
      [ "MemoryReaderBehavior", "class_minty_1_1_memory_reader_behavior.html", "class_minty_1_1_memory_reader_behavior" ],
      [ "MemoryStack", "class_minty_1_1_memory_stack.html", "class_minty_1_1_memory_stack" ],
      [ "MemoryStackBuilder", "struct_minty_1_1_memory_stack_builder.html", "struct_minty_1_1_memory_stack_builder" ],
      [ "MemoryWriterBehavior", "class_minty_1_1_memory_writer_behavior.html", "class_minty_1_1_memory_writer_behavior" ],
      [ "Node", "class_minty_1_1_node.html", "class_minty_1_1_node" ],
      [ "NodeReaderBehavior", "class_minty_1_1_node_reader_behavior.html", "class_minty_1_1_node_reader_behavior" ],
      [ "Owner", "class_minty_1_1_owner.html", "class_minty_1_1_owner" ],
      [ "Pair", "class_minty_1_1_pair.html", "class_minty_1_1_pair" ],
      [ "Parseable", "class_minty_1_1_parseable.html", "class_minty_1_1_parseable" ],
      [ "Path", "class_minty_1_1_path.html", "class_minty_1_1_path" ],
      [ "PhysicalFile", "class_minty_1_1_physical_file.html", "class_minty_1_1_physical_file" ],
      [ "Queue", "class_minty_1_1_queue.html", "class_minty_1_1_queue" ],
      [ "Reader", "class_minty_1_1_reader.html", "class_minty_1_1_reader" ],
      [ "ReaderFormatBehavior", "class_minty_1_1_reader_format_behavior.html", "class_minty_1_1_reader_format_behavior" ],
      [ "ReaderImplementation", "class_minty_1_1_reader_implementation.html", "class_minty_1_1_reader_implementation" ],
      [ "ReaderStorageBehavior", "class_minty_1_1_reader_storage_behavior.html", "class_minty_1_1_reader_storage_behavior" ],
      [ "Ref", "class_minty_1_1_ref.html", "class_minty_1_1_ref" ],
      [ "Serializable", "class_minty_1_1_serializable.html", "class_minty_1_1_serializable" ],
      [ "SerializableObject", "class_minty_1_1_serializable_object.html", "class_minty_1_1_serializable_object" ],
      [ "Set", "class_minty_1_1_set.html", "class_minty_1_1_set" ],
      [ "Stack", "class_minty_1_1_stack.html", "class_minty_1_1_stack" ],
      [ "StaticContainer", "class_minty_1_1_static_container.html", "class_minty_1_1_static_container" ],
      [ "String", "class_minty_1_1_string.html", "class_minty_1_1_string" ],
      [ "Text", "class_minty_1_1_text.html", "class_minty_1_1_text" ],
      [ "TextBuilder", "struct_minty_1_1_text_builder.html", "struct_minty_1_1_text_builder" ],
      [ "TextReaderBehavior", "class_minty_1_1_text_reader_behavior.html", "class_minty_1_1_text_reader_behavior" ],
      [ "TextWriterBehavior", "class_minty_1_1_text_writer_behavior.html", "class_minty_1_1_text_writer_behavior" ],
      [ "UUID", "class_minty_1_1_u_u_i_d.html", "class_minty_1_1_u_u_i_d" ],
      [ "Variable", "class_minty_1_1_variable.html", "class_minty_1_1_variable" ],
      [ "Vector", "class_minty_1_1_vector.html", "class_minty_1_1_vector" ],
      [ "VirtualFile", "class_minty_1_1_virtual_file.html", "class_minty_1_1_virtual_file" ],
      [ "Wrap", "class_minty_1_1_wrap.html", "class_minty_1_1_wrap" ],
      [ "Wrapper", "class_minty_1_1_wrapper.html", "class_minty_1_1_wrapper" ],
      [ "Writer", "class_minty_1_1_writer.html", "class_minty_1_1_writer" ],
      [ "WriterFormatBehavior", "class_minty_1_1_writer_format_behavior.html", "class_minty_1_1_writer_format_behavior" ],
      [ "WriterImplementation", "class_minty_1_1_writer_implementation.html", "class_minty_1_1_writer_implementation" ],
      [ "WriterStorageBehavior", "class_minty_1_1_writer_storage_behavior.html", "class_minty_1_1_writer_storage_behavior" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Minty::Color >", "structstd_1_1hash_3_01_minty_1_1_color_01_4.html", "structstd_1_1hash_3_01_minty_1_1_color_01_4" ],
      [ "hash< Minty::Owner< T > >", "structstd_1_1hash_3_01_minty_1_1_owner_3_01_t_01_4_01_4.html", "structstd_1_1hash_3_01_minty_1_1_owner_3_01_t_01_4_01_4" ],
      [ "hash< Minty::Path >", "structstd_1_1hash_3_01_minty_1_1_path_01_4.html", "structstd_1_1hash_3_01_minty_1_1_path_01_4" ],
      [ "hash< Minty::Ref< T > >", "structstd_1_1hash_3_01_minty_1_1_ref_3_01_t_01_4_01_4.html", "structstd_1_1hash_3_01_minty_1_1_ref_3_01_t_01_4_01_4" ],
      [ "hash< Minty::String >", "structstd_1_1hash_3_01_minty_1_1_string_01_4.html", "structstd_1_1hash_3_01_minty_1_1_string_01_4" ],
      [ "hash< Minty::UUID >", "structstd_1_1hash_3_01_minty_1_1_u_u_i_d_01_4.html", "structstd_1_1hash_3_01_minty_1_1_u_u_i_d_01_4" ]
    ] ]
];