var annotated_dup =
[
    [ "Minty", "namespace_minty.html", [
      [ "Application", "class_minty_1_1_application.html", "class_minty_1_1_application" ],
      [ "ApplicationBuilder", "struct_minty_1_1_application_builder.html", "struct_minty_1_1_application_builder" ],
      [ "ArgumentParser", "class_minty_1_1_argument_parser.html", "class_minty_1_1_argument_parser" ],
      [ "Array", "class_minty_1_1_array.html", "class_minty_1_1_array" ],
      [ "Asset", "class_minty_1_1_asset.html", "class_minty_1_1_asset" ],
      [ "AssetManager", "class_minty_1_1_asset_manager.html", "class_minty_1_1_asset_manager" ],
      [ "AssetManagerBuilder", "struct_minty_1_1_asset_manager_builder.html", "struct_minty_1_1_asset_manager_builder" ],
      [ "Buffer", "class_minty_1_1_buffer.html", "class_minty_1_1_buffer" ],
      [ "BufferBuilder", "struct_minty_1_1_buffer_builder.html", "struct_minty_1_1_buffer_builder" ],
      [ "Camera", "class_minty_1_1_camera.html", "class_minty_1_1_camera" ],
      [ "CameraBuilder", "struct_minty_1_1_camera_builder.html", "struct_minty_1_1_camera_builder" ],
      [ "Color", "struct_minty_1_1_color.html", "struct_minty_1_1_color" ],
      [ "ConstantContainer", "class_minty_1_1_constant_container.html", "class_minty_1_1_constant_container" ],
      [ "Container", "class_minty_1_1_container.html", "class_minty_1_1_container" ],
      [ "Context", "class_minty_1_1_context.html", "class_minty_1_1_context" ],
      [ "ContextBuilder", "struct_minty_1_1_context_builder.html", "struct_minty_1_1_context_builder" ],
      [ "Counter", "class_minty_1_1_counter.html", "class_minty_1_1_counter" ],
      [ "Debug", "class_minty_1_1_debug.html", "class_minty_1_1_debug" ],
      [ "DualBuffer", "class_minty_1_1_dual_buffer.html", "class_minty_1_1_dual_buffer" ],
      [ "DynamicContainer", "class_minty_1_1_dynamic_container.html", "class_minty_1_1_dynamic_container" ],
      [ "Event", "class_minty_1_1_event.html", "class_minty_1_1_event" ],
      [ "File", "class_minty_1_1_file.html", "class_minty_1_1_file" ],
      [ "FileReaderBehavior", "class_minty_1_1_file_reader_behavior.html", "class_minty_1_1_file_reader_behavior" ],
      [ "FileWriterBehavior", "class_minty_1_1_file_writer_behavior.html", "class_minty_1_1_file_writer_behavior" ],
      [ "GenericAsset", "class_minty_1_1_generic_asset.html", "class_minty_1_1_generic_asset" ],
      [ "GenericAssetBuilder", "struct_minty_1_1_generic_asset_builder.html", "struct_minty_1_1_generic_asset_builder" ],
      [ "Image", "class_minty_1_1_image.html", "class_minty_1_1_image" ],
      [ "ImageBuilder", "struct_minty_1_1_image_builder.html", "struct_minty_1_1_image_builder" ],
      [ "is_parseable", "struct_minty_1_1is__parseable.html", null ],
      [ "is_parseable< T, std::enable_if_t< std::is_base_of_v< Parseable, T > > >", "struct_minty_1_1is__parseable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_01_parseable_00_01_t_01_4_01_4_01_4.html", null ],
      [ "is_serializable", "struct_minty_1_1is__serializable.html", null ],
      [ "is_serializable< T, std::enable_if_t< std::is_base_of_v< Serializable, T > > >", "struct_minty_1_1is__serializable_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__of__v_3_0e61b24cf8de0099628fc4627104c54f1.html", null ],
      [ "is_serializable_object", "struct_minty_1_1is__serializable__object.html", null ],
      [ "is_serializable_object< T, std::enable_if_t< std::is_base_of_v< SerializableObject, T > > >", "struct_minty_1_1is__serializable__object_3_01_t_00_01std_1_1enable__if__t_3_01std_1_1is__base__o8b98ea3f58746b2d0c5b18654dddd28a.html", null ],
      [ "JobManager", "class_minty_1_1_job_manager.html", "class_minty_1_1_job_manager" ],
      [ "JobManagerBuilder", "struct_minty_1_1_job_manager_builder.html", "struct_minty_1_1_job_manager_builder" ],
      [ "List", "class_minty_1_1_list.html", "class_minty_1_1_list" ],
      [ "Manager", "class_minty_1_1_manager.html", "class_minty_1_1_manager" ],
      [ "Map", "class_minty_1_1_map.html", "class_minty_1_1_map" ],
      [ "Material", "class_minty_1_1_material.html", "class_minty_1_1_material" ],
      [ "MaterialBuilder", "struct_minty_1_1_material_builder.html", "struct_minty_1_1_material_builder" ],
      [ "MaterialTemplate", "class_minty_1_1_material_template.html", "class_minty_1_1_material_template" ],
      [ "MaterialTemplateBuilder", "struct_minty_1_1_material_template_builder.html", "struct_minty_1_1_material_template_builder" ],
      [ "MemoryContainer", "class_minty_1_1_memory_container.html", "class_minty_1_1_memory_container" ],
      [ "MemoryManager", "class_minty_1_1_memory_manager.html", "class_minty_1_1_memory_manager" ],
      [ "MemoryManagerBuilder", "struct_minty_1_1_memory_manager_builder.html", "struct_minty_1_1_memory_manager_builder" ],
      [ "MemoryPool", "class_minty_1_1_memory_pool.html", "class_minty_1_1_memory_pool" ],
      [ "MemoryPoolBuilder", "struct_minty_1_1_memory_pool_builder.html", "struct_minty_1_1_memory_pool_builder" ],
      [ "MemoryReaderBehavior", "class_minty_1_1_memory_reader_behavior.html", "class_minty_1_1_memory_reader_behavior" ],
      [ "MemoryStack", "class_minty_1_1_memory_stack.html", "class_minty_1_1_memory_stack" ],
      [ "MemoryStackBuilder", "struct_minty_1_1_memory_stack_builder.html", "struct_minty_1_1_memory_stack_builder" ],
      [ "MemoryWriterBehavior", "class_minty_1_1_memory_writer_behavior.html", "class_minty_1_1_memory_writer_behavior" ],
      [ "Node", "class_minty_1_1_node.html", "class_minty_1_1_node" ],
      [ "NodeReaderBehavior", "class_minty_1_1_node_reader_behavior.html", "class_minty_1_1_node_reader_behavior" ],
      [ "Owner", "class_minty_1_1_owner.html", "class_minty_1_1_owner" ],
      [ "Pair", "class_minty_1_1_pair.html", "class_minty_1_1_pair" ],
      [ "Parseable", "class_minty_1_1_parseable.html", "class_minty_1_1_parseable" ],
      [ "Path", "class_minty_1_1_path.html", "class_minty_1_1_path" ],
      [ "PhysicalFile", "class_minty_1_1_physical_file.html", "class_minty_1_1_physical_file" ],
      [ "Queue", "class_minty_1_1_queue.html", "class_minty_1_1_queue" ],
      [ "Reader", "class_minty_1_1_reader.html", "class_minty_1_1_reader" ],
      [ "ReaderFormatBehavior", "class_minty_1_1_reader_format_behavior.html", "class_minty_1_1_reader_format_behavior" ],
      [ "ReaderImplementation", "class_minty_1_1_reader_implementation.html", "class_minty_1_1_reader_implementation" ],
      [ "ReaderStorageBehavior", "class_minty_1_1_reader_storage_behavior.html", "class_minty_1_1_reader_storage_behavior" ],
      [ "Ref", "class_minty_1_1_ref.html", "class_minty_1_1_ref" ],
      [ "RenderAttachment", "struct_minty_1_1_render_attachment.html", "struct_minty_1_1_render_attachment" ],
      [ "Renderer", "class_minty_1_1_renderer.html", null ],
      [ "RenderManager", "class_minty_1_1_render_manager.html", "class_minty_1_1_render_manager" ],
      [ "RenderManagerBuilder", "struct_minty_1_1_render_manager_builder.html", "struct_minty_1_1_render_manager_builder" ],
      [ "RenderPass", "class_minty_1_1_render_pass.html", "class_minty_1_1_render_pass" ],
      [ "RenderPassBuilder", "struct_minty_1_1_render_pass_builder.html", "struct_minty_1_1_render_pass_builder" ],
      [ "RenderTarget", "class_minty_1_1_render_target.html", "class_minty_1_1_render_target" ],
      [ "RenderTargetBuilder", "struct_minty_1_1_render_target_builder.html", "struct_minty_1_1_render_target_builder" ],
      [ "Serializable", "class_minty_1_1_serializable.html", "class_minty_1_1_serializable" ],
      [ "SerializableObject", "class_minty_1_1_serializable_object.html", "class_minty_1_1_serializable_object" ],
      [ "Set", "class_minty_1_1_set.html", "class_minty_1_1_set" ],
      [ "Shader", "class_minty_1_1_shader.html", "class_minty_1_1_shader" ],
      [ "ShaderAttribute", "struct_minty_1_1_shader_attribute.html", "struct_minty_1_1_shader_attribute" ],
      [ "ShaderBinding", "struct_minty_1_1_shader_binding.html", "struct_minty_1_1_shader_binding" ],
      [ "ShaderBuilder", "struct_minty_1_1_shader_builder.html", "struct_minty_1_1_shader_builder" ],
      [ "ShaderInput", "struct_minty_1_1_shader_input.html", "struct_minty_1_1_shader_input" ],
      [ "ShaderModule", "class_minty_1_1_shader_module.html", "class_minty_1_1_shader_module" ],
      [ "ShaderModuleBuilder", "struct_minty_1_1_shader_module_builder.html", "struct_minty_1_1_shader_module_builder" ],
      [ "ShaderVertexInput", "struct_minty_1_1_shader_vertex_input.html", "struct_minty_1_1_shader_vertex_input" ],
      [ "Stack", "class_minty_1_1_stack.html", "class_minty_1_1_stack" ],
      [ "StaticContainer", "class_minty_1_1_static_container.html", "class_minty_1_1_static_container" ],
      [ "Stopwatch", "class_minty_1_1_stopwatch.html", "class_minty_1_1_stopwatch" ],
      [ "String", "class_minty_1_1_string.html", "class_minty_1_1_string" ],
      [ "Surface", "class_minty_1_1_surface.html", "class_minty_1_1_surface" ],
      [ "SurfaceBuilder", "struct_minty_1_1_surface_builder.html", "struct_minty_1_1_surface_builder" ],
      [ "TextReaderBehavior", "class_minty_1_1_text_reader_behavior.html", "class_minty_1_1_text_reader_behavior" ],
      [ "TextWriterBehavior", "class_minty_1_1_text_writer_behavior.html", "class_minty_1_1_text_writer_behavior" ],
      [ "Time", "class_minty_1_1_time.html", "class_minty_1_1_time" ],
      [ "Transform", "class_minty_1_1_transform.html", "class_minty_1_1_transform" ],
      [ "UUID", "class_minty_1_1_u_u_i_d.html", "class_minty_1_1_u_u_i_d" ],
      [ "Variable", "class_minty_1_1_variable.html", "class_minty_1_1_variable" ],
      [ "Vector", "class_minty_1_1_vector.html", "class_minty_1_1_vector" ],
      [ "Viewport", "class_minty_1_1_viewport.html", "class_minty_1_1_viewport" ],
      [ "ViewportBuilder", "struct_minty_1_1_viewport_builder.html", "struct_minty_1_1_viewport_builder" ],
      [ "VirtualFile", "class_minty_1_1_virtual_file.html", "class_minty_1_1_virtual_file" ],
      [ "Vulkan_Buffer", "class_minty_1_1_vulkan___buffer.html", "class_minty_1_1_vulkan___buffer" ],
      [ "Vulkan_Frame", "struct_minty_1_1_vulkan___frame.html", "struct_minty_1_1_vulkan___frame" ],
      [ "Vulkan_Image", "class_minty_1_1_vulkan___image.html", "class_minty_1_1_vulkan___image" ],
      [ "Vulkan_Material", "class_minty_1_1_vulkan___material.html", "class_minty_1_1_vulkan___material" ],
      [ "Vulkan_QueueFamilyIndices", "struct_minty_1_1_vulkan___queue_family_indices.html", "struct_minty_1_1_vulkan___queue_family_indices" ],
      [ "Vulkan_Renderer", "class_minty_1_1_vulkan___renderer.html", null ],
      [ "Vulkan_RenderManager", "class_minty_1_1_vulkan___render_manager.html", "class_minty_1_1_vulkan___render_manager" ],
      [ "Vulkan_RenderPass", "class_minty_1_1_vulkan___render_pass.html", "class_minty_1_1_vulkan___render_pass" ],
      [ "Vulkan_RenderTarget", "class_minty_1_1_vulkan___render_target.html", "class_minty_1_1_vulkan___render_target" ],
      [ "Vulkan_Shader", "class_minty_1_1_vulkan___shader.html", "class_minty_1_1_vulkan___shader" ],
      [ "Vulkan_ShaderModule", "class_minty_1_1_vulkan___shader_module.html", "class_minty_1_1_vulkan___shader_module" ],
      [ "Vulkan_Surface", "class_minty_1_1_vulkan___surface.html", "class_minty_1_1_vulkan___surface" ],
      [ "Vulkan_SwapchainSupportDetails", "struct_minty_1_1_vulkan___swapchain_support_details.html", "struct_minty_1_1_vulkan___swapchain_support_details" ],
      [ "Vulkan_Viewport", "class_minty_1_1_vulkan___viewport.html", "class_minty_1_1_vulkan___viewport" ],
      [ "Window", "class_minty_1_1_window.html", "class_minty_1_1_window" ],
      [ "WindowBuilder", "struct_minty_1_1_window_builder.html", "struct_minty_1_1_window_builder" ],
      [ "WindowCloseEvent", "class_minty_1_1_window_close_event.html", "class_minty_1_1_window_close_event" ],
      [ "WindowResizeEvent", "class_minty_1_1_window_resize_event.html", "class_minty_1_1_window_resize_event" ],
      [ "Windows_Window", "class_minty_1_1_windows___window.html", "class_minty_1_1_windows___window" ],
      [ "Wrap", "class_minty_1_1_wrap.html", "class_minty_1_1_wrap" ],
      [ "Wrapper", "class_minty_1_1_wrapper.html", "class_minty_1_1_wrapper" ],
      [ "Writer", "class_minty_1_1_writer.html", "class_minty_1_1_writer" ],
      [ "WriterFormatBehavior", "class_minty_1_1_writer_format_behavior.html", "class_minty_1_1_writer_format_behavior" ],
      [ "WriterImplementation", "class_minty_1_1_writer_implementation.html", "class_minty_1_1_writer_implementation" ],
      [ "WriterStorageBehavior", "class_minty_1_1_writer_storage_behavior.html", "class_minty_1_1_writer_storage_behavior" ]
    ] ],
    [ "std", "namespacestd.html", [
      [ "hash< Minty::Color >", "structstd_1_1hash_3_01_minty_1_1_color_01_4.html", "structstd_1_1hash_3_01_minty_1_1_color_01_4" ],
      [ "hash< Minty::Owner< T > >", "structstd_1_1hash_3_01_minty_1_1_owner_3_01_t_01_4_01_4.html", "structstd_1_1hash_3_01_minty_1_1_owner_3_01_t_01_4_01_4" ],
      [ "hash< Minty::Path >", "structstd_1_1hash_3_01_minty_1_1_path_01_4.html", "structstd_1_1hash_3_01_minty_1_1_path_01_4" ],
      [ "hash< Minty::Ref< T > >", "structstd_1_1hash_3_01_minty_1_1_ref_3_01_t_01_4_01_4.html", "structstd_1_1hash_3_01_minty_1_1_ref_3_01_t_01_4_01_4" ],
      [ "hash< Minty::String >", "structstd_1_1hash_3_01_minty_1_1_string_01_4.html", "structstd_1_1hash_3_01_minty_1_1_string_01_4" ],
      [ "hash< Minty::UUID >", "structstd_1_1hash_3_01_minty_1_1_u_u_i_d_01_4.html", "structstd_1_1hash_3_01_minty_1_1_u_u_i_d_01_4" ]
    ] ]
];